### ISSUE TITLE
aop_style() não lida bem com quebra de linha usando \n

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/urbanformbr#10]
Exemplo:
```{r}
source("R/style.R")

library(ggplot2)

ToothGrowth$dose <- as.factor(ToothGrowth$dose)

ggplot(ToothGrowth, aes(x=dose, y=len, color=dose)) + 
  geom_boxplot() +
  labs(title='Title test with a\nbreak', color='Legend\ntest') +
  aop_style() +
  theme(legend.position = 'right')
 
```

![Rplot](https://user-images.githubusercontent.com/7448421/114759251-51226180-9d34-11eb-9102-a18ecb19dbdc.png)

**Comment by joaoparga** [comment]
Acho que podemos contornar isso usando a sintaxe do pacote `ggtext`, cuja função `element_markdown` (usada em `aop_style`) interpreta o texto como markdown. "To start a new line, use the `<br>` tag or add two spaces before the end of a line.", de https://github.com/wilkelab/ggtext.

Exemplo: 

`ggplot(mpg, aes(cty, hwy, colour = as.factor(cyl))) + 
  geom_point() +
  labs(title = 'Primeira linha <br> segunda linha', colour = "Primeira linha <br> segunda linha") +
  aop_style() +
  theme(legend.position = 'right')`

![exemplo_ggtext](https://user-images.githubusercontent.com/60621364/114761590-153ccb80-9d37-11eb-9bf0-6a6ea246eefc.png)

**Comment by rafapereirabr** [comment]
Boa! Então é só substituir o `\n` por `<br>`.   Cc @Joaobazzo

**Comment by rafapereirabr** [comment]
valeu. Fechando esse issue
