### ISSUE TITLE
Por que usar  "| is.na(V0221)" aqui ?

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/urbanformbr#13]
https://github.com/ipeaGIT/urbanformbr/blob/2c0a412f5b029bd254a90708466aecc534d46adc/R/pca_regression_analysis/00_11_censo.R#L144

Oi Joao, precisa usar esse `| is.na(V0221)` nessa parte do código?

**Comment by joaoparga** [comment]
Oi @rafapereirabr . De fato não precisa utilizar, não faz diferença no resultado gerado. Acho que tinha deixado para facilitar a leitura.
Já retirei do código.
