### ISSUE TITLE
proporcao de domicilios com veículo

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/urbanformbr#15]
https://github.com/ipeaGIT/urbanformbr/blob/2c0a412f5b029bd254a90708466aecc534d46adc/R/pca_regression_analysis/00_11_censo.R#L595

Oi @joaoparga . To pensando aqui, acho que faz mais sentido medir as variáves de motos e carros no censo como a proporção de **domicílios** que possuem ao menos um veiculo( um variavel pra carro e outra pra moto).

Acho que faz mais sentido medir em termos de proporção de domicilios  (ao invés de pessoas) porque na prática a gente nao mede frota por pessoas né. E se a gente se foca em pessoas em domicilios com ao menos um veiculo, daí um domicilio com varias pessoas acaba sendo contabilizado varias vezes (embora a gente nao saiba a quantidade de veiculos). 

o que acha?

**Comment by joaoparga** [comment]
Faz sentido, @rafapereirabr. É verdade, não tinha considerado a questão da múltipla contagem dos domicílios. Como você falou, de fato não estamos medindo acesso de indivíduos aos veículos, mas do domicílio mesmo.

Acabei de fazer a modificação no código: variáveis `x_prop_motos_pes` e `x_prop_autos_pes` passaram pra `x_prop_motos_dom` e `x_prop_autos_dom`.

**Comment by rafapereirabr** [comment]
ótimo. Voce poderia por favor rodar o código para atuzalizar a tabela de dados salva no servidor?

**Comment by joaoparga** [comment]
Havia esquicido de commitar, @rafapereirabr, perdão. Acabei de dar push e salvei a base.
